export const LABELS: { [key: string]: string } = {
  firstName: "First Name",
  lastName: "Last Name",
  emailId: "Email",
  phoneNumber: "Phone",
  nationality: "Nationality",
  currentResidence: "Current Residence ",
  idNumber: "ID Number",
  dateOfBirth: "Date of Birth",
  gender: "Gender",
  Paragraph: "Paragraph",
  ShortAnswer: "Short Answer",
  YesNo: "Yes or No",
  Dropdown: "Dropdown",
  MultipleChoice: "Multiple Choice",
  Date: "Date",
  Number: "Number",
  FileUpload: "File Upload",
  education: "Education",
  experience: "Experience",
  resume: "Resume",
};

export const QUESTIONTYPES = [
  { value: "Paragraph", label: "Paragraph" },
  { value: "ShortAnswer", label: "Short Answer" },
  { value: "YesNo", label: "Yes or No" },
  { value: "Dropdown", label: "Dropdown" },
  { value: "MultipleChoice", label: "Multiple Choice" },
  { value: "Date", label: "Date" },
  { value: "Number", label: "Number" },
  { value: "FileUpload", label: "File Upload" },
];
